create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.access_levels (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  priority integer not null default 100,
  is_default boolean not null default false,
  can_view_dashboard boolean not null default true,
  can_manage_operations boolean not null default false,
  can_access_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint access_levels_code_format check (code ~ '^[a-z0-9_\-]+$')
);

create unique index if not exists access_levels_one_default_idx
on public.access_levels (is_default)
where is_default = true;

create table if not exists public.user_access_levels (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  access_level_id bigint not null references public.access_levels(id) on delete restrict,
  status text not null default 'active',
  assigned_by uuid references auth.users(id) on delete set null,
  assigned_at timestamptz not null default now(),
  expires_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_access_levels_status_check check (status in ('active', 'inactive', 'expired', 'suspended')),
  constraint user_access_levels_one_level_per_user unique (user_id)
);

create index if not exists user_access_levels_access_level_id_idx
on public.user_access_levels (access_level_id);

create index if not exists user_access_levels_status_idx
on public.user_access_levels (status);

drop trigger if exists set_access_levels_updated_at on public.access_levels;
create trigger set_access_levels_updated_at
before update on public.access_levels
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_user_access_levels_updated_at on public.user_access_levels;
create trigger set_user_access_levels_updated_at
before update on public.user_access_levels
for each row
execute function public.set_current_timestamp_updated_at();

insert into public.access_levels (
  code,
  name,
  description,
  priority,
  is_default,
  can_view_dashboard,
  can_manage_operations,
  can_access_admin
)
values
  ('operator', 'Operator', 'Default production dashboard access', 100, true, true, false, false),
  ('supervisor', 'Supervisor', 'Operational oversight for production lines and machines', 70, false, true, true, false),
  ('engineer', 'Engineer', 'Engineering access for troubleshooting and optimization', 50, false, true, true, false),
  ('admin', 'Admin', 'Factory system administrator', 1, false, true, true, true)
on conflict (code) do update
set
  name = excluded.name,
  description = excluded.description,
  priority = excluded.priority,
  is_default = excluded.is_default,
  can_view_dashboard = excluded.can_view_dashboard,
  can_manage_operations = excluded.can_manage_operations,
  can_access_admin = excluded.can_access_admin,
  updated_at = now();

create or replace function public.is_factory_admin()
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  current_uid uuid;
begin
  current_uid := auth.uid();

  if current_uid is not null and exists (
    select 1
    from public.user_access_levels membership
    join public.access_levels level on level.id = membership.access_level_id
    where membership.user_id = current_uid
      and membership.status = 'active'
      and level.can_access_admin = true
  ) then
    return true;
  end if;

  return
    coalesce((auth.jwt() -> 'app_metadata' ->> 'role') in ('admin', 'superadmin', 'owner'), false)
    or coalesce((auth.jwt() -> 'user_metadata' ->> 'role') in ('admin', 'superadmin', 'owner'), false)
    or coalesce((auth.jwt() -> 'app_metadata' ->> 'is_admin') in ('true', '1'), false)
    or coalesce((auth.jwt() -> 'user_metadata' ->> 'is_admin') in ('true', '1'), false);
end;
$$;

create or replace function public.assign_default_access_level()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_access_level_id bigint;
begin
  select id
  into default_access_level_id
  from public.access_levels
  where is_default = true
  order by priority asc
  limit 1;

  if default_access_level_id is not null then
    insert into public.user_access_levels (
      user_id,
      access_level_id,
      status,
      assigned_at,
      notes
    )
    values (
      new.id,
      default_access_level_id,
      'active',
      now(),
      'Auto assigned default access level'
    )
    on conflict (user_id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists assign_default_access_level_on_signup on auth.users;
create trigger assign_default_access_level_on_signup
after insert on auth.users
for each row
execute function public.assign_default_access_level();

alter table public.access_levels enable row level security;
alter table public.user_access_levels enable row level security;

drop policy if exists "access_levels_select_authenticated" on public.access_levels;
create policy "access_levels_select_authenticated"
on public.access_levels
for select
to authenticated
using (true);

drop policy if exists "access_levels_admin_manage" on public.access_levels;
create policy "access_levels_admin_manage"
on public.access_levels
for all
to authenticated
using (public.is_factory_admin())
with check (public.is_factory_admin());

drop policy if exists "user_access_levels_select_own_or_admin" on public.user_access_levels;
create policy "user_access_levels_select_own_or_admin"
on public.user_access_levels
for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_factory_admin()
);

drop policy if exists "user_access_levels_admin_manage" on public.user_access_levels;
create policy "user_access_levels_admin_manage"
on public.user_access_levels
for all
to authenticated
using (public.is_factory_admin())
with check (public.is_factory_admin());

comment on table public.access_levels is 'Access levels for production dashboard users';
comment on table public.user_access_levels is 'Assignments between auth users and dashboard access levels';
