create table if not exists public.machines (
  id bigint generated by default as identity primary key,
  code text unique,
  name text not null,
  model text,
  spec text,
  zone text,
  area text,
  location text,
  section text,
  line text,
  line_name text,
  status text default 'stop',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists machines_name_idx on public.machines(name);
create index if not exists machines_zone_idx on public.machines(zone);
create index if not exists machines_line_idx on public.machines(line);

create table if not exists public.machine_alarm (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines(id) on delete cascade,
  alarm_code text,
  alarm_name text not null,
  severity text default 'alarm',
  note text,
  start_time timestamptz not null default now(),
  end_time timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists machine_alarm_machine_id_idx on public.machine_alarm(machine_id);
create index if not exists machine_alarm_start_time_idx on public.machine_alarm(start_time desc);
create index if not exists machine_alarm_end_time_idx on public.machine_alarm(end_time);

create table if not exists public.machine_status_log (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines(id) on delete cascade,
  status text not null,
  efficiency numeric(5,2),
  note text,
  timestamp timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists machine_status_log_machine_id_idx on public.machine_status_log(machine_id);
create index if not exists machine_status_log_timestamp_idx on public.machine_status_log(timestamp desc);

create table if not exists public.machine_oee_daily (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines(id) on delete cascade,
  date date not null,
  availability numeric(5,2) default 0,
  performance numeric(5,2) default 0,
  quality numeric(5,2) default 0,
  oee numeric(5,2) default 0,
  efficiency numeric(5,2) default 0,
  oee_percent numeric(5,2) generated always as (oee) stored,
  created_at timestamptz not null default now(),
  unique (machine_id, date)
);

create index if not exists machine_oee_daily_machine_id_idx on public.machine_oee_daily(machine_id);
create index if not exists machine_oee_daily_date_idx on public.machine_oee_daily(date desc);

create table if not exists public.machine_status (
  id bigint generated by default as identity primary key,
  machine_id bigint references public.machines(id) on delete cascade,
  machine_name text,
  line text,
  line_name text,
  station text not null,
  status text not null,
  efficiency numeric(5,2),
  oee numeric(5,2),
  note text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists machine_status_line_idx on public.machine_status(line);
create index if not exists machine_status_station_idx on public.machine_status(station);
create index if not exists machine_status_updated_at_idx on public.machine_status(updated_at desc);

create table if not exists public.production_daily (
  id bigint generated by default as identity primary key,
  production_date date not null default current_date,
  total_production integer not null default 0,
  efficiency numeric(5,2) default 0,
  production_rate numeric(10,2) default 0,
  avg_cycle_time numeric(10,2) default 0,
  created_at timestamptz not null default now(),
  unique (production_date)
);

create index if not exists production_daily_date_idx on public.production_daily(production_date desc);
create index if not exists production_daily_created_at_idx on public.production_daily(created_at desc);

create table if not exists public.movement_efficiency (
  id bigint generated by default as identity primary key,
  production_date date not null default current_date,
  hour integer not null check (hour between 0 and 23),
  value numeric(5,2) not null default 0,
  created_at timestamptz not null default now(),
  unique (production_date, hour)
);

create index if not exists movement_efficiency_date_idx on public.movement_efficiency(production_date desc);
create index if not exists movement_efficiency_created_at_idx on public.movement_efficiency(created_at desc);

create table if not exists public.loss_time (
  id bigint generated by default as identity primary key,
  production_date date not null default current_date,
  breakdown numeric(5,2) default 0,
  tool_change numeric(5,2) default 0,
  model_change numeric(5,2) default 0,
  q_adjust numeric(5,2) default 0,
  created_at timestamptz not null default now(),
  unique (production_date)
);

create index if not exists loss_time_date_idx on public.loss_time(production_date desc);
create index if not exists loss_time_created_at_idx on public.loss_time(created_at desc);

create table if not exists public.line_efficiency (
  id bigint generated by default as identity primary key,
  production_date date not null default current_date,
  line_name text not null,
  line text,
  efficiency numeric(5,2) not null default 0,
  oee numeric(5,2),
  value numeric(5,2),
  created_at timestamptz not null default now()
);

create index if not exists line_efficiency_line_name_idx on public.line_efficiency(line_name);
create index if not exists line_efficiency_date_idx on public.line_efficiency(production_date desc);
create index if not exists line_efficiency_created_at_idx on public.line_efficiency(created_at desc);

create table if not exists public.machine_layout_point (
  id bigint generated by default as identity primary key,
  machine_id bigint not null references public.machines(id) on delete cascade,
  label text,
  x numeric(6,2) not null,
  y numeric(6,2) not null,
  status text default 'normal',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists machine_layout_point_machine_id_idx on public.machine_layout_point(machine_id);

create table if not exists public.air_compressor (
  id bigint generated by default as identity primary key,
  pressure numeric(10,2),
  temperature numeric(10,2),
  status text,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists air_compressor_created_at_idx on public.air_compressor(created_at desc);
